import React, { useState } from 'react';
import { Sparkles, ChevronDown, ChevronUp, Bot } from 'lucide-react';

interface AiSummaryBoxProps {
  text: string;
}

export const AiSummaryBox: React.FC<AiSummaryBoxProps> = ({ text }) => {
  const [isOpen, setIsOpen] = useState(true);

  return (
    <div className="mb-10 bg-gradient-to-br from-zinc-900 to-zinc-950 border border-zinc-800 rounded-sm overflow-hidden shadow-sm">
      <div 
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center justify-between px-6 py-3 bg-zinc-900 border-b border-zinc-800 cursor-pointer hover:bg-zinc-800/50 transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="p-1.5 bg-indigo-500/10 rounded text-indigo-400">
            <Sparkles size={18} />
          </div>
          <h3 className="font-serif text-lg font-bold text-indigo-100 tracking-wide">
            AI总结摘要
          </h3>
        </div>
        <div className="text-zinc-500">
            {isOpen ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
        </div>
      </div>
      
      {isOpen && (
        <div className="p-6 md:p-8 flex gap-6">
            <div className="hidden md:flex flex-col items-center justify-start pt-1 text-zinc-600">
                <Bot size={32} strokeWidth={1.5} />
                <div className="h-full w-[1px] bg-zinc-800 mt-4"></div>
            </div>
            <div className="flex-1">
                <p className="font-serif text-xl leading-relaxed text-zinc-300 text-justify">
                    <span className="text-4xl float-left mr-2 mt-[-10px] text-indigo-500 font-bold">T</span>
                    {text}
                </p>
                <div className="mt-4 flex justify-end">
                    <span className="text-xs font-mono text-zinc-600">Generated by Gemini Pro • 80ms</span>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};